import type { Program, RadioStation, PodcastCategory, CategoryId } from "./types";
import { BookOpen, Scale, Scroll, Mic2, Radio } from "lucide-react";

export const CATEGORIES: { id: CategoryId; label: string; icon: React.ReactNode; color: string }[] = [
  { id: "quran",   label: "تفسير القرآن",       icon: <BookOpen size={16} />, color: "#10b981" },
  { id: "dawah",   label: "دعوية وإيمانية",      icon: <Mic2 size={16} />,    color: "#8b5cf6" },
  { id: "fatwa",   label: "فتاوى وأحكام",        icon: <Scale size={16} />,   color: "#f59e0b" },
  { id: "stories", label: "قصص وسيرة",           icon: <Scroll size={16} />,  color: "#ef4444" },
  { id: "radio",   label: "إذاعية",              icon: <Radio size={16} />,   color: "#3b82f6" },
];

export const PROGRAMS: Program[] = [
  { id: "p1",  name: "لعلهم يفقهون",         host: "د. عمر عبد الكافي", category: "quran",  featured: true, hot: true, badge: "الأشهر",  color: "#064e3b", colorTo: "#065f46", icon: "📖" },
  { id: "p2",  name: "في رحاب سورة",          host: "د. راغب السرجاني",  category: "quran",  featured: true,                              color: "#065f46", colorTo: "#047857", icon: "🌿" },
  { id: "p3",  name: "خواطر",                 host: "أحمد الشقيري",      category: "quran",  featured: true, hot: true, badge: "تريند",   color: "#1e3a5f", colorTo: "#1e40af", icon: "✨" },
  { id: "p4",  name: "تفسير الشعراوي",        host: "الشيخ الشعراوي",    category: "quran",  featured: true,            badge: "أيقونة",  color: "#3b0764", colorTo: "#6d28d9", icon: "📜" },
  { id: "p5",  name: "نور على نور",           category: "quran",                                                                            color: "#166534", colorTo: "#15803d", icon: "💡" },
  { id: "p6",  name: "بينات",                 category: "quran",                                                                            color: "#1e3a5f", colorTo: "#1d4ed8", icon: "🔆" },
  { id: "p7",  name: "القرآن علم وعمل",       category: "quran",                                                                            color: "#422006", colorTo: "#92400e", icon: "🧠" },
  { id: "p8",  name: "مع القرآن",             category: "quran",                                                                            color: "#14532d", colorTo: "#166534", icon: "🌙" },
  { id: "p9",  name: "آيات بينات",            category: "quran",                                                                            color: "#1c1917", colorTo: "#292524", icon: "🌟" },
  { id: "p10", name: "ورتل القرآن ترتيلا",    category: "quran",                                                                            color: "#0c4a6e", colorTo: "#0369a1", icon: "🎵" },

  { id: "p11", name: "سواعد الإخاء",          host: "نخبة دعاة",          category: "dawah",  featured: true, hot: true, badge: "ملتهب",   color: "#7c2d12", colorTo: "#b45309", icon: "🤝" },
  { id: "p12", name: "الحصن",                 category: "dawah",                                                                            color: "#1e3a8a", colorTo: "#1d4ed8", icon: "🏰" },
  { id: "p13", name: "قلوب عامرة",            category: "dawah",                                                                            color: "#4a1942", colorTo: "#7c3aed", icon: "❤️" },
  { id: "p14", name: "يحب الجمال",            category: "dawah",                                                                            color: "#0f172a", colorTo: "#1e293b", icon: "🌸" },
  { id: "p15", name: "الإمام الطيب",          host: "شيخ الأزهر",         category: "dawah",  featured: true,                              color: "#1c3326", colorTo: "#15803d", icon: "👳" },
  { id: "p16", name: "مصر أرض المجددين",      category: "dawah",                                                                            color: "#1e3a5f", colorTo: "#1e40af", icon: "🇪🇬" },
  { id: "p17", name: "البناء الإيماني",       category: "dawah",                                                                            color: "#422006", colorTo: "#d97706", icon: "🏗️" },
  { id: "p18", name: "الطريق إلى الله",       category: "dawah",                                                                            color: "#0c0a09", colorTo: "#1c1917", icon: "🌄" },
  { id: "p19", name: "كنوز السنة",            category: "dawah",                                                                            color: "#3b0764", colorTo: "#7c3aed", icon: "💎" },
  { id: "p20", name: "رسالة إلى الله",        category: "dawah",                                                                            color: "#0c4a6e", colorTo: "#0284c7", icon: "📩" },

  { id: "p21", name: "اسأل مع دعاء",          category: "fatwa", featured: true,                                                            color: "#422006", colorTo: "#b45309", icon: "❓" },
  { id: "p22", name: "فتاوى على الهواء",       category: "fatwa",                                                                            color: "#1a1a2e", colorTo: "#16213e", icon: "📡" },
  { id: "p23", name: "الجواب الكافي",          category: "fatwa",                                                                            color: "#14532d", colorTo: "#15803d", icon: "✅" },
  { id: "p24", name: "الدين والحياة",          category: "fatwa",                                                                            color: "#1e3a8a", colorTo: "#2563eb", icon: "⚖️" },
  { id: "p25", name: "فاسألوا أهل الذكر",     category: "fatwa",                                                                            color: "#3b0764", colorTo: "#6d28d9", icon: "🧑‍🏫" },
  { id: "p26", name: "بين السائل والفقيه",     category: "fatwa",                                                                            color: "#0c4a6e", colorTo: "#0369a1", icon: "🗣️" },
  { id: "p27", name: "مع الناس",               category: "fatwa",                                                                            color: "#166534", colorTo: "#16a34a", icon: "👥" },
  { id: "p28", name: "فتاوى رمضان",            category: "fatwa",                                                                            color: "#78350f", colorTo: "#d97706", icon: "🌙" },
  { id: "p29", name: "نور الفتاوى",            category: "fatwa",                                                                            color: "#0c0a09", colorTo: "#44403c", icon: "🕯️" },
  { id: "p30", name: "الشريعة والحياة",        category: "fatwa",                                                                            color: "#1e3a5f", colorTo: "#1e40af", icon: "📋" },

  { id: "p31", name: "قصص الأنبياء",           category: "stories", featured: true, hot: true, badge: "خالد",                              color: "#064e3b", colorTo: "#065f46", icon: "📚" },
  { id: "p32", name: "السيرة النبوية",          category: "stories", featured: true,            badge: "مميز",                              color: "#1c1917", colorTo: "#44403c", icon: "🌹" },
  { id: "p33", name: "رجال حول الرسول",        category: "stories",                                                                          color: "#422006", colorTo: "#b45309", icon: "⚔️" },
  { id: "p34", name: "عمر (وثائقي درامي)",     category: "stories", featured: true, hot: true, badge: "ملحمي",                              color: "#1a1a2e", colorTo: "#16213e", icon: "🎬" },
  { id: "p35", name: "حياة الصحابة",           category: "stories",                                                                          color: "#14532d", colorTo: "#166534", icon: "🌟" },
  { id: "p36", name: "قصص القرآن",             category: "stories",                                                                          color: "#0c4a6e", colorTo: "#0369a1", icon: "📖" },
  { id: "p37", name: "ثم اهتديت",              category: "stories",                                                                          color: "#3b0764", colorTo: "#7c3aed", icon: "🕊️" },
  { id: "p38", name: "أعلام الإسلام",          category: "stories",                                                                          color: "#1e3a8a", colorTo: "#1d4ed8", icon: "🏆" },
  { id: "p39", name: "مساجد من التاريخ",       category: "stories",                                                                          color: "#166534", colorTo: "#15803d", icon: "🕌" },
  { id: "p40", name: "مساجد الشرقية",          category: "stories",                                                                          color: "#422006", colorTo: "#92400e", icon: "🏛️" },

  { id: "p41", name: "نور على الدرب",          host: "ابن باز & ابن عثيمين", category: "radio", featured: true, hot: true, badge: "أسطوري", color: "#0c4a6e", colorTo: "#0369a1", icon: "📻" },
  { id: "p42", name: "حديث الصباح",            category: "radio",                                                                            color: "#78350f", colorTo: "#f59e0b", icon: "🌅" },
  { id: "p43", name: "قطوف إيمانية",           category: "radio",                                                                            color: "#14532d", colorTo: "#16a34a", icon: "🌾" },
  { id: "p44", name: "خواطر إسلامية",          category: "radio",                                                                            color: "#1e3a5f", colorTo: "#1e40af", icon: "💭" },
  { id: "p45", name: "دين ودنيا",              category: "radio",                                                                            color: "#1c1917", colorTo: "#292524", icon: "🌍" },
  { id: "p46", name: "رسالة الإسلام",          category: "radio",                                                                            color: "#064e3b", colorTo: "#065f46", icon: "📨" },
  { id: "p47", name: "التلاوة والتفسير",       category: "radio",                                                                            color: "#422006", colorTo: "#b45309", icon: "🎙️" },
  { id: "p48", name: "فقه الحياة",             category: "radio",                                                                            color: "#3b0764", colorTo: "#6d28d9", icon: "🔬" },
  { id: "p49", name: "مع القرآن الكريم",       category: "radio",                                                                            color: "#166534", colorTo: "#15803d", icon: "📿" },
  { id: "p50", name: "دقائق إيمانية",          category: "radio",                                                                            color: "#0c0a09", colorTo: "#1c1917", icon: "⏱️" },
];

export const FEATURED = PROGRAMS.filter((p) => p.featured);

export const LIVE_QURAN_RADIOS: RadioStation[] = [
  {
    id: "radio-cairo",
    name: "إذاعة القرآن من القاهرة",
    url: "https://stream.radiojar.com/8s5u5tpdtwzuv.mp3",
    logo: "https://play-lh.googleusercontent.com/2JbGhJox4i9yljgqANaAHBIv_7z1KekZ5PS9bZxxU1jsPktIHAJcX-VvVunEqUtN6Q5BPu8vCpcEBZXHais3mw=w240-h480-rw",
    color: "#059669",
    colorTo: "#10b981",
  },
  {
    id: "radio-saudi",
    name: "إذاعة القرآن من السعودية",
    url: "https://stream.radiojar.com/0tpy1h0kxtzuv.mp3",
    logo: "https://i1.sndcdn.com/avatars-EbeDM9V1tVVw7gAE-yibBcg-t1080x1080.jpg",
    color: "#059669",
    colorTo: "#10b981",
  },
  {
    id: "radio-zayed",
    name: "إذاعة زايد للقرآن الكريم",
    url: "https://zayedquran.gov.ae/stream.php",
    logo: "https://radio.qassimy.com/wp-content/uploads/2023/03/%D8%A7%D8%B0%D8%A7%D8%B9%D8%A9-%D8%B2%D8%A7%D9%8A%D8%AF-%D9%84%D9%84%D9%82%D8%B1%D8%A7%D9%86-%D8%A7%D9%84%D9%83%D8%B1%D9%8A%D9%85-%D8%A7%D9%84%D9%81%D8%AC%D9%8A%D8%B1%D8%A9-%D8%A8%D8%AB-%D9%85%D8%A8%D8%A7%D8%B4%D8%B1.jpg",
    color: "#d97706",
    colorTo: "#f59e0b",
  },
  {
    id: "radio-shaarawy",
    name: "تفسير الشعراوي",
    url: "https://backup.qurango.net/radio/gareeb-quran",
    logo: "https://upload.wikimedia.org/wikipedia/ar/9/98/%D8%AA%D9%81%D8%B3%D9%8A%D8%B1_%D8%A7%D9%84%D8%B4%D8%B9%D8%B1%D8%A7%D9%88%D9%8A.jpg",
    color: "#7c3aed",
    colorTo: "#a78bfa",
  },
  {
    id: "radio-maher",
    name: "ماهر المعيقلي",
    url: "https://backup.qurango.net/radio/maher",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3ASajh9nryVVmHm4nWfb0NXtAIaWpVGD6XQ&s",
    color: "#059669",
    colorTo: "#10b981",
  },
  {
    id: "radio-abdulbasit",
    name: "عبدالباسط عبد الصمد",
    url: "https://backup.qurango.net/radio/abdulbasit_abdulsamad_mojawwad",
    logo: "https://azhar.eg/Portals/fatwacenter/EasyDNNnews/89286/img-468451147_973787668116279_4470673895227883327_n.jpg",
    color: "#d97706",
    colorTo: "#f59e0b",
  },
];

export const PODCAST_CATEGORIES: PodcastCategory[] = [
  {
    id: "ala-khuta",
    title: "علي خطي الرسول",
    imageUrl: "https://islamicaudio.net/ar/media/show/1316",
    description:
      "بين مكة والمدينة، وبين البعثة والانتقال إلى الرفيق الأعلى، خطواتٌ كثيرةٌ مشاها نبُّينا عليه الصلاة والسلام متوكلا على الله عاملًا بما أمر، صادعًا بالحق صابرًا على ما أصابه، هنا نتتبع خطوات رسول الله ﷺ؛ نفتش في دواوين السنة ونصغي لرواة السيرة، لنحقق الاتباع ونسير على الطريق.",
    color: "#064e3b",
    colorTo: "#065f46",
    episodes: [
      { id: "yom-alfrkan", title: "يوم الفرقان", imageUrl: "https://islamicaudio.net/assets/media/yom-alfrkan1017_mediumThumb.jpg", description: "يوم الفرقان يوم غزوة بدر الكبرى.. يوم شفى الله فيه صدور المسلمين من الكفار", mediaUrl: "https://islamicaudio.net/assets/media/yom-alfrkan866.mp3" },
      { id: "hkm-alamyn", title: "حكم الأمين", imageUrl: "https://islamicaudio.net/assets/media/hkm-alamyn1029_mediumThumb.jpg", description: "كان حكم الأمين ﷺ حجة على كفار قريش..", mediaUrl: "https://islamicaudio.net/assets/media/hkm-alamyn871.mp3" },
      { id: "fth-mka", title: "فتح مكة", imageUrl: "https://islamicaudio.net/assets/media/fth-mk1020_mediumThumb.jpg", description: "فتح مكة تحقيق لوعد الله لنبيِّه ﷺ..", mediaUrl: "https://islamicaudio.net/assets/media/fth-mk868.mp3" },
      { id: "slh-alhdyby", title: "صلح الحديبية", imageUrl: "https://islamicaudio.net/assets/media/slh-alhdyby1022_mediumThumb.jpg", description: "الصُّلح الذي وصفه الله تعالى بالفتح المبين..", mediaUrl: "https://islamicaudio.net/assets/media/slh-alhdyby874.mp3" },
      { id: "mhajron-oansar", title: "مهاجرون وأنصار", imageUrl: "https://islamicaudio.net/assets/media/mhajron-oansar1021_mediumThumb.jpg", description: "المهاجرون والأنصار وتآخيهم قصة فريدة في تاريخ البشر..", mediaUrl: "https://islamicaudio.net/assets/media/mhajron-oansar864.mp3" },
      { id: "ghrb-aleyman", title: "غربة الإيمان", imageUrl: "https://islamicaudio.net/assets/media/ghrb-alayman1023_mediumThumb.jpg", description: "غُربة الإيمان.. حيث آلام الغربة أفضل من الفتنة في الدين", mediaUrl: "https://islamicaudio.net/assets/media/ghrb-aleyman869.mp3" },
      { id: "alrfyk-alaaal", title: "الرفيق الأعلى", imageUrl: "https://islamicaudio.net/assets/media/alrfyk-alaaal1024_mediumThumb.jpg", description: "\"اللهم الرفيق الأعلى\" قالها النبي ﷺ حين وفاته..", mediaUrl: "https://islamicaudio.net/assets/media/alrfyk-alaaal861.mp3" },
      { id: "aaam-alfyl", title: "عام الفيل", imageUrl: "https://islamicaudio.net/assets/media/aaam-alfyl1018_mediumThumb.jpg", description: "عام الفيل الذي شهد مولد النبي ﷺ..", mediaUrl: "https://islamicaudio.net/assets/media/aaam-alfyl870.mp3" },
      { id: "hadth-alafk", title: "حادثة الإفك", imageUrl: "https://islamicaudio.net/assets/media/hadth-alafk1019_mediumThumb.jpg", description: "حادثة الإفك.. حادثة من الحوادث المهمة التي أنزل فيها القرآن..", mediaUrl: "https://islamicaudio.net/assets/media/hadth-alafk872.mp3" },
      { id: "asyr-yasr-alklob", title: "أسير يأسر القلوب", imageUrl: "https://islamicaudio.net/assets/media/whatsapp-image-2021-12-03-at-102159-am741_mediumThumb.jpeg", description: "غدرت هذيل بسريَّة من عشرة من خيرة صحابة النبي ﷺ...", mediaUrl: "https://islamicaudio.net/assets/media/asyr-yasr-alklob860.mp3" },
      { id: "alhjr", title: "الهجرة", imageUrl: "https://islamicaudio.net/assets/media/whatsapp-image-2021-12-03-at-102158-am740_mediumThumb.jpeg", description: "الهجرة..حيث هجر الأهل والأصحاب والدار...", mediaUrl: "https://islamicaudio.net/assets/media/alhjr862.mp3" },
      { id: "kola-thkyla", title: "قولا ثقيلا", imageUrl: "https://islamicaudio.net/assets/media/kola-thkyla1025_mediumThumb.jpg", description: "كانت مَهمَّة النبي ﷺ تبليغ الدعوة...", mediaUrl: "https://islamicaudio.net/assets/media/kola-thkyla867.mp3" },
      { id: "bd-alohy", title: "بدء الوحي", imageUrl: "https://islamicaudio.net/assets/media/bd-alohy1028_mediumThumb.jpg", description: "بَدْءُ الوحي وانطلاق نور الإسلام...", mediaUrl: "https://islamicaudio.net/assets/media/bd-alohy863.mp3" },
      { id: "maark-ahd", title: "معركة أحد", imageUrl: "https://islamicaudio.net/assets/media/maark-ahd1027_mediumThumb.jpg", description: "نزل القرآن يوجِّه المؤمنين بعد معركة أُحد...", mediaUrl: "https://islamicaudio.net/assets/media/maark-ahd865.mp3" },
      { id: "byaa-alaakb", title: "بيعة العقبة", imageUrl: "https://islamicaudio.net/assets/media/byaa-alaakb1026_mediumThumb.jpg", description: "بيعة العقبة مرحلة مفصلية في تاريخ الإسلام..", mediaUrl: "https://islamicaudio.net/assets/media/byaa-alaakb873.mp3" },
    ],
  },
  {
    id: "shrfat",
    title: "شرفات",
    imageUrl: "https://islamicaudio.net/ar/media/show/1314",
    description: "بودكاست من المستقبل، يبثُّ فينا الأمل، نحكي عبرَه قصصًا ملونة لأولئك الملهمين الذين يطوفون الأرض حاملين رسالة الإسلام..",
    color: "#1e3a5f",
    colorTo: "#1e40af",
    episodes: [
      { id: "fy-lj-albhr", title: "في لج البحر", imageUrl: "https://islamicaudio.net/assets/media/shrfat-13705_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/13-fy-lj-albhr-aaaly-aldk849.mp3" },
      { id: "slaty-alaol", title: "صلاتي الأولى", imageUrl: "https://islamicaudio.net/assets/media/shrfat-02694_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/02-slaty-alaol-aaaly-aldk858.mp3" },
      { id: "ahthr-theb", title: "احذر ذئب اللحظة المناسبة", imageUrl: "https://islamicaudio.net/assets/media/shrfat-12704_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/12-ahthr-theb-allhth-almnasb-aaaly-aldk848.mp3" },
      { id: "hl-jrbt", title: "هل جربت هذه التجارة", imageUrl: "https://islamicaudio.net/assets/media/shrfat-10702_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/10-hl-jrbt-hthh-altjar-aaaly-aldk851.mp3" },
      { id: "htha-alsaek", title: "هذا السائق", imageUrl: "https://islamicaudio.net/assets/media/shrfat-07699_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/07-htha-alsaek-aaaly-aldk853.mp3" },
      { id: "kraan-alfjr", title: "قرآن الفجر", imageUrl: "https://islamicaudio.net/assets/media/shrfat-06698_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/06-kraan-alfjr-aaaly-aldk856.mp3" },
      { id: "ma-aaajz", title: "هذا ما أعجز عن التعبير عنه", imageUrl: "https://islamicaudio.net/assets/media/shrfat-08700_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/08-htha-ma-aaajz-aan-altaabyr-aanh-aaaly-aldk847.mp3" },
      { id: "asbagh", title: "إسباغ المكاره على القلب", imageUrl: "https://islamicaudio.net/assets/media/shrfat-11703_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/11-asbagh-almkarh-aal-alklb-aaaly-aldk852.mp3" },
      { id: "ma-akthr-alfyl", title: "ما أكثر الفيلة", imageUrl: "https://islamicaudio.net/assets/media/shrfat-09701_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/09-ma-akthr-alfyl-aaaly-aldk850.mp3" },
      { id: "faadt-al-nfsy", title: "فعدت إلى نفسي", imageUrl: "https://islamicaudio.net/assets/media/shrfat-03695_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/03-faadt-al-nfsy-aaaly-aldk857.mp3" },
      { id: "sot-sadh", title: "صوت صادح في سبيل الله", imageUrl: "https://islamicaudio.net/assets/media/shrfat-16707_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/16-sot-sadh-fy-sbyl-allh-aaaly-aldk845.mp3" },
      { id: "syarty-alkdym", title: "سيارتي القديمة وشيخي الراوي", imageUrl: "https://islamicaudio.net/assets/media/shrfat-01693_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/01-syarty-alkdym-oshykhy-alraoy-aaaly-aldk859.mp3" },
      { id: "aaash-aamrh", title: "عاش عمره كله للدعوة", imageUrl: "https://islamicaudio.net/assets/media/shrfat-04696_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/04-aaash-aamrh-klh-lldaao-aaaly-aldk855.mp3" },
      { id: "adaay-amy", title: "أدعية أمي المضطرة", imageUrl: "https://islamicaudio.net/assets/media/shrfat-05697_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/05-adaay-amy-almdtr-aaaly-aldk854.mp3" },
      { id: "ma-alhya", title: "ما الحياة إلا خفقات", imageUrl: "https://islamicaudio.net/assets/media/shrfat-15706_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/15-ma-alhya-ala-khfkat-aaaly-aldk846.mp3" },
    ],
  },
  {
    id: "mtka",
    title: "مُتكأ",
    imageUrl: "https://islamicaudio.net/ar/media/show/1313",
    description: "بودكاست يحكي قصص أعلام النبلاء، يغوص في التاريخ تارة، وتارة أخري يستكشف الحاضر، لكن بوصلته دومًا في اتجاه واحد.",
    color: "#0c4a6e",
    colorTo: "#0369a1",
    episodes: [
      { id: "abn-aljozy", title: "ابن الجوزي", imageUrl: "https://islamicaudio.net/assets/media/mtka-08715_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/08-abn-aljozy-aaaly-aldk839.mp3" },
      { id: "alkady-shryh", title: "القاضي شريح", imageUrl: "https://islamicaudio.net/assets/media/mtka-16723_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/16-alkady-shryh-aaaly-aldk829.mp3" },
      { id: "alnooy", title: "النووي", imageUrl: "https://islamicaudio.net/assets/media/mtka-09716_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/09-alnooy-aaaly-aldk836.mp3" },
      { id: "albkhary", title: "البخاري", imageUrl: "https://islamicaudio.net/assets/media/mtka-11718_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/11-albkhary-aaaly-aldk834.mp3" },
      { id: "alshafaay", title: "الإمام الشافعي", imageUrl: "https://islamicaudio.net/assets/media/mtka-06713_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/06-alamam-alshafaay-aaaly-aldk838.mp3" },
      { id: "alaasklany", title: "ابن حجر العسقلاني", imageUrl: "https://islamicaudio.net/assets/media/mtka-10717_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/10-alaasklany-aaaly-aldk835.mp3" },
      { id: "sfyan-althory", title: "سفيان الثوري", imageUrl: "https://islamicaudio.net/assets/media/mtka-01708_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/01-sfyan-althory-aaaly-aldk844.mp3" },
      { id: "aabd-allh-bn-aabas", title: "عبد الله بن عباس", imageUrl: "https://islamicaudio.net/assets/media/mtka-04711_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/04-aabd-allh-bn-aabas-aaaly-aldk840.mp3" },
      { id: "aby-alolyd", title: "أبو الوليد الدمشقي", imageUrl: "https://islamicaudio.net/assets/media/mtka-03710_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/03-aby-alolyd-aldmshky-aaaly-aldk843.mp3" },
      { id: "ahmd-bn-hnyl", title: "الإمام أحمد بن حنبل", imageUrl: "https://islamicaudio.net/assets/media/mtka-12719_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/12-ahmd-bn-hnyl-aaaly-aldk833.mp3" },
      { id: "asd-bn-frat", title: "أسد بن الفرات", imageUrl: "https://islamicaudio.net/assets/media/mtka-07714_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/07-asd-bn-frat-aaaly-aldk837.mp3" },
      { id: "aby-hatm", title: "أبو حاتم الرَّازِي", imageUrl: "https://islamicaudio.net/assets/media/mtka-02709_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/02-mhmd-alrazy-aaaly-aldk841.mp3" },
      { id: "alsmaaany", title: "أبو المظفر السَّمعاني", imageUrl: "https://islamicaudio.net/assets/media/mtka-15722_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/15-alsmaaany-aaaly-aldk830.mp3" },
      { id: "alkyroany", title: "ابن فَرُّوخ القيرواني", imageUrl: "https://islamicaudio.net/assets/media/mtka-14721_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/14-alkyroany-aaaly-aldk832.mp3" },
      { id: "almalky", title: "المالكي", imageUrl: "https://islamicaudio.net/assets/media/mtka-13720_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/13-almalky-aaaly-aldk831.mp3" },
    ],
  },
  {
    id: "alwan",
    title: "ألوان",
    imageUrl: "https://islamicaudio.net/ar/media/show/1320",
    description: "لطالما كانت (أروان) محطة للمتنقلين في صحراء أفريقيا... هنا بودكاست يقطف قصص المسلمين الجدد من حدائق الحياة.",
    color: "#be185d",
    colorTo: "#f472b6",
    episodes: [
      { id: "aabd-allh-batrsby", title: "عبد الله باترسبي", imageUrl: "https://islamicaudio.net/assets/media/aroan-002725_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/02-aabd-allh-batrsby-aaaly-aldk827.mp3" },
      { id: "ayfon-rydly", title: "إيفون ريدلي", imageUrl: "https://islamicaudio.net/assets/media/aroan-011734_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/11-ayfon-rydly-aaaly-aldk818.mp3" },
      { id: "kolz", title: "فيرونيك كولز", imageUrl: "https://islamicaudio.net/assets/media/aroan-010733_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/10-kolz-aaaly-aldk819.mp3" },
      { id: "malma", title: "مالما", imageUrl: "https://islamicaudio.net/assets/media/aroan-005728_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/05-malma-aaaly-aldk824.mp3" },
      { id: "danyal-mor", title: "دانيال مور", imageUrl: "https://islamicaudio.net/assets/media/aroan-003726_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/03-danyal-mor-aaaly-aldk826.mp3" },
      { id: "manyos", title: "عبد الكريم مانيوس", imageUrl: "https://islamicaudio.net/assets/media/aroan-007730_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/07-aabd-alkrym-manyos-aaaly-aldk822.mp3" },
      { id: "shhyr", title: "شهيرة صلاح الدين", imageUrl: "https://islamicaudio.net/assets/media/aroan-016739_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/16-shhyr-slah-aldyn813.mp3" },
      { id: "am-allh", title: "أَمَة الله", imageUrl: "https://islamicaudio.net/assets/media/aroan-013736_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/13-am-allh-aaaly-aldk816.mp3" },
      { id: "abrahym-syly", title: "إبراهيم سيلي", imageUrl: "https://islamicaudio.net/assets/media/aroan-009732_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/09-abrahym-syly-aaaly-aldk820.mp3" },
      { id: "aaly-slman", title: "علي سلمان", imageUrl: "https://islamicaudio.net/assets/media/aroan-001724_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/01-aaly-slman-aaaly-aldk828.mp3" },
      { id: "aaly-rmdan", title: "علي رمضان", imageUrl: "https://islamicaudio.net/assets/media/aroan-015738_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/15-aaly-rmdan-aaaly-aldk814.mp3" },
      { id: "mrym-aljmyl", title: "مريم الجميلة", imageUrl: "https://islamicaudio.net/assets/media/aroan-014737_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/14-mrym-aljmyl-aaaly-aldk815.mp3" },
      { id: "jonar", title: "محمد جونار إريكسون", imageUrl: "https://islamicaudio.net/assets/media/aroan-008731_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/08-mhmd-jonar-arykson-aaaly-aldk821.mp3" },
      { id: "aaly-krysa", title: "علي كريسا", imageUrl: "https://islamicaudio.net/assets/media/aroan-012735_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/12-aaly-krysa-aaaly-aldk817.mp3" },
      { id: "hadly-farok", title: "هادلي فاروق", imageUrl: "https://islamicaudio.net/assets/media/aroan-004727_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/04-hadly-farok-aaaly-aldk825.mp3" },
      { id: "dyams", title: "ديامس", imageUrl: "https://islamicaudio.net/assets/media/aroan-006729_mediumThumb.jpg", mediaUrl: "https://islamicaudio.net/assets/media/06-dyams-aaaly-aldk823.mp3" },
    ],
  },
];
